# Generated by Django 5.2.4 on 2025-07-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projetofinal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="username",
        ),
        migrations.AddField(
            model_name="usuario",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="verified"),
        ),
        migrations.AddField(
            model_name="usuario",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Gerencia"),
                    ("LEAD", "Lider de Equipe"),
                    ("MEMBER", "Membro"),
                    ("GUEST", "Acesso Limitado"),
                ],
                default="MEMBER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="convite",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Gerencia"),
                    ("LEAD", "Lider de Equipe"),
                    ("MEMBER", "Membro"),
                    ("GUEST", "Acesso Limitado"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="convite",
            name="token",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="last name"),
        ),
    ]
